# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-03-08 17:49
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('bots', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bot',
            name='bot_type',
            field=models.CharField(choices=[('FAQ Bot', 'Faq'), ('Tone Bot', 'Tone'), ('Culture Bot', 'Culture')], default='Faq', max_length=9),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bot',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2016, 3, 8, 17, 49, 31, 764369, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bot',
            name='description',
            field=models.CharField(default='han', max_length=255),
            preserve_default=False,
        ),
    ]
