# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-03-04 04:26
from __future__ import unicode_literals

import django.contrib.postgres.fields.ranges
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bots', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='azizbot',
            name='ages',
            field=django.contrib.postgres.fields.ranges.FloatRangeField(blank=True, null=True),
        ),
    ]
