# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-29 20:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bots', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='botcollection',
            name='aziz_bot',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='bots.AzizBot'),
        ),
    ]
